<?php
	$this->headTitle('Login');
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.watermark.min.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/login.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('/css/login.css'));
	$this->hideLogoutLink = true;
?>
<div>
	<form action="<?= $this->url() ?>" method="post">
		<input type="text" name="username" id="username" autocomplete="off" />
		<br />
		<input type="password" name="password" id="password" />
		<br />
		<input type="submit" name="login" id="login" value="Login" />
	</form>
</div>