<?php
/*
	$uploadifyScript = "
		$(document).ready(function() {
		  $('#file_upload').uploadify({
		    'uploader'  : '/uploadify/uploadify.swf',
		    'script'    : '/uploadify/uploadify.php',
		    'cancelImg' : '/uploadify/cancel.png',
		    'folder'    : '/factory-wheels.images/" . $this->wheel->getId() . "-" . $this->wheel->getFolder() . "',
		    'multi'		: true
		  });
		});

	";

	$this->headScript()->appendFile($this->baseUrl('/uploadify/swfobject.js'));
	$this->headScript()->appendFile($this->baseUrl('/uploadify/jquery.uploadify.v2.1.4.min.js'));
	$this->headScript()->appendScript($uploadifyScript);

	$path = '/factory-wheels.images/' . $this->wheel->getId() . '-' . $this->wheel->getFolder() . '/';
	echo 'path: ' . $path . '<br>';
	echo 'exists: ' . file_exists($path) . '<br>';

	if (!file_exists($path)) {
		mkdir ($path, 0755);
	}

<input id="file_upload" type="file" name="file_upload" />
<input type="button" value="Upload" onclick="$('#file_upload').uploadifyUpload();" />

	*/
?>

To do: Uploadify